pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - status-success=deploy/netlify
      - status-success=Mixed content
    actions:
      merge:
        method: merge
